import random
import requests

# Dictionary mapping ISO country codes to Spanish-speaking country names
spanish_speaking_countries = {
    "AR": "Argentina",
    "BO": "Bolivia",
    "CL": "Chile",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "GT": "Guatemala",
    "HN": "Honduras",
    "MX": "Mexico",
    "NI": "Nicaragua",
    "PA": "Panama",
    "PY": "Paraguay",
    "PE": "Peru",
    "ES": "Spain",
    "UY": "Uruguay",
    "VE": "Venezuela"
}

# Dictionary mapping ISO country codes to French-speaking country names
french_speaking_countries = {
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "BJ": "Benin",
    "CA": "Canada",
    "CF": "Central African Republic",
    "CG": "Republic of the Congo",
    "CI": "Ivory Coast",
    "CM": "Cameroon",
    "DJ": "Djibouti",
    "FR": "France",
    "GA": "Gabon",
    "GN": "Guinea",
    "KM": "Comoros",
    "LU": "Luxembourg",
    "MG": "Madagascar",
    "ML": "Mali",
    "MU": "Mauritius",
    "NE": "Niger",
    "RW": "Rwanda",
    "SN": "Senegal",
    "TD": "Chad",
    "TG": "Togo",
    "VU": "Vanuatu",
    "MC": "Monaco",
    "CD": "Democratic Republic of the Congo",
    "CH": "Switzerland",
    "SE": "Seychelles"
}

# Dictionary mapping ISO country codes to English-speaking country names
english_speaking_countries = {
    "AU": "Australia",
    "BS": "Bahamas",
    "BB": "Barbados",
    "BZ": "Belize",
    "BW": "Botswana",
    "CA": "Canada",
    "DM": "Dominica",
    "FJ": "Fiji",
    "GM": "Gambia",
    "GH": "Ghana",
    "GD": "Grenada",
    "GY": "Guyana",
    "IN": "India",
    "IE": "Ireland",
    "JM": "Jamaica",
    "KE": "Kenya",
    "KI": "Kiribati",
    "LS": "Lesotho",
    "LR": "Liberia",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MU": "Mauritius",
    "FM": "Micronesia",
    "NA": "Namibia",
    "NR": "Nauru",
    "NZ": "New Zealand",
    "NG": "Nigeria",
    "PK": "Pakistan",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "RW": "Rwanda",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SB": "Solomon Islands",
    "ZA": "South Africa",
    "SS": "South Sudan",
    "LK": "Sri Lanka",
    "SZ": "Eswatini (Swaziland)",
    "TZ": "Tanzania",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "UG": "Uganda",
    "GB": "United Kingdom",
    "US": "United States",
    "VU": "Vanuatu",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}

# Dictionary mapping ISO country codes to Arabic-speaking country names
arabic_speaking_countries = {
    "DZ": "Algeria",
    "BH": "Bahrain",
    "DJ": "Djibouti",
    "EG": "Egypt",
    "ER": "Eritrea",
    "IQ": "Iraq",
    "JO": "Jordan",
    "KW": "Kuwait",
    "LB": "Lebanon",
    "LY": "Libya",
    "MA": "Morocco",
    "MR": "Mauritania",
    "OM": "Oman",
    "PS": "Palestine",
    "QA": "Qatar",
    "SA": "Saudi Arabia",
    "SD": "Sudan",
    "SY": "Syria",
    "TD": "Chad",
    "YE": "Yemen"
}